"""empty message

Revision ID: 879e88d5047a
Revises: e9329eac5d63
Create Date: 2025-07-08 15:56:29.895406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879e88d5047a'
down_revision = 'e9329eac5d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('hastags', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'profile', ['profile_id'], ['id'])

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=60), nullable=False))
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profile_id')
        batch_op.drop_column('hastags')
        batch_op.drop_column('caption')

    op.drop_table('hashtag')
    # ### end Alembic commands ###
