"""empty message

Revision ID: ad53ecb4ab2d
Revises: 60e042fc5723
Create Date: 2025-07-08 16:38:59.142971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad53ecb4ab2d'
down_revision = '60e042fc5723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reel_hashtag',
    sa.Column('reel_id', sa.Integer(), nullable=True),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], ),
    sa.ForeignKeyConstraint(['reel_id'], ['reel.id'], )
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('hastags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hastags', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    op.drop_table('reel_hashtag')
    op.drop_table('reel')
    # ### end Alembic commands ###
